/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Parking (void);

////////////////


GtkWidget* create_RHwindowParky (void);
GtkWidget* create_RHwindowAvis_Reclamation (void);
