/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Parking (void)
{
  GtkWidget *Parking;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *entry_nompark;
  GtkWidget *entry_idpark;
  GtkWidget *entry_nbrdispopark;
  GtkWidget *entry_prixpark;
  GtkWidget *labelmsg;
  GtkWidget *combobox_typepark;
  GtkWidget *combobox_etatpark;
  GtkWidget *entry_capacite;
  GtkWidget *btn_ajouterpark;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label44;
  GtkWidget *label16;
  GtkWidget *label40;
  GtkWidget *label39;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label41;
  GtkWidget *checkbuttonconf;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label43;
  GtkWidget *label42;
  GtkWidget *label_message;
  GtkWidget *button_confmodpark;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label45;
  GtkWidget *button3;
  GtkWidget *image15;
  GtkWidget *label47;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *entry_search_park;
  GtkWidget *btn_supp;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label51;
  GtkWidget *btn_modif;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label50;
  GtkWidget *btn_search_park;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image9;
  GtkWidget *label53;
  GtkWidget *btn_aff;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label49;
  GtkWidget *label52;
  GtkWidget *label46;
  GtkWidget *fixed4;
  GtkWidget *treeview3;
  GtkWidget *entry_nom_agent;
  GtkWidget *entry_id_agent;
  GtkWidget *entry_nom_parking;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *button1;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label57;
  GtkWidget *button2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label58;
  GtkWidget *label48;

  Parking = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Parking), _("parking"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Parking), fixed1);
  gtk_widget_set_size_request (fixed1, 700, 500);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 8);
  gtk_widget_set_size_request (notebook1, 1000, 500);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry_nompark = gtk_entry_new ();
  gtk_widget_show (entry_nompark);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nompark, 136, 168);
  gtk_widget_set_size_request (entry_nompark, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nompark), 8226);

  entry_idpark = gtk_entry_new ();
  gtk_widget_show (entry_idpark);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_idpark, 136, 80);
  gtk_widget_set_size_request (entry_idpark, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idpark), 8226);

  entry_nbrdispopark = gtk_entry_new ();
  gtk_widget_show (entry_nbrdispopark);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nbrdispopark, 504, 288);
  gtk_widget_set_size_request (entry_nbrdispopark, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nbrdispopark), 8226);

  entry_prixpark = gtk_entry_new ();
  gtk_widget_show (entry_prixpark);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_prixpark, 504, 80);
  gtk_widget_set_size_request (entry_prixpark, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prixpark), 8226);

  labelmsg = gtk_label_new ("");
  gtk_widget_show (labelmsg);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmsg, 400, 520);
  gtk_widget_set_size_request (labelmsg, 220, 40);

  combobox_typepark = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_typepark);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_typepark, 504, 152);
  gtk_widget_set_size_request (combobox_typepark, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_typepark), _("Sous sol"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_typepark), _("R\303\251sidentiel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_typepark), _("Priv\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_typepark), _("Public"));

  combobox_etatpark = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_etatpark);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_etatpark, 128, 256);
  gtk_widget_set_size_request (combobox_etatpark, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_etatpark), _("Ouvert"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_etatpark), _("Ferm\303\251"));

  entry_capacite = gtk_entry_new ();
  gtk_widget_show (entry_capacite);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_capacite, 504, 224);
  gtk_widget_set_size_request (entry_capacite, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_capacite), 8226);

  btn_ajouterpark = gtk_button_new ();
  gtk_widget_show (btn_ajouterpark);
  gtk_fixed_put (GTK_FIXED (fixed2), btn_ajouterpark, 32, 384);
  gtk_widget_set_size_request (btn_ajouterpark, 184, 64);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_ajouterpark), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">AJOUTER</span>"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox1), label44, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label16 = gtk_label_new (_("<span\n color=\"DARKBLUE\"font=\"11\"weight=\"bold\">Bienvenu Au Parking:</span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 248, 8);
  gtk_widget_set_size_request (label16, 220, 48);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label40 = gtk_label_new (_("<span color=\"BLACK\"font=\"11\"weight=\"normal\">Type de parking</span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed2), label40, 368, 152);
  gtk_widget_set_size_request (label40, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label39 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Prix Park</span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed2), label39, 360, 80);
  gtk_widget_set_size_request (label39, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  label36 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Id Parking</span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed2), label36, 24, 80);
  gtk_widget_set_size_request (label36, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Nom parking</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed2), label37, 24, 168);
  gtk_widget_set_size_request (label37, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Etat</span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed2), label38, 16, 264);
  gtk_widget_set_size_request (label38, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label41 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Capacite</span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed2), label41, 360, 216);
  gtk_widget_set_size_request (label41, 104, 40);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  checkbuttonconf = gtk_check_button_new ();
  gtk_widget_show (checkbuttonconf);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbuttonconf, 40, 336);
  gtk_widget_set_size_request (checkbuttonconf, 136, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (checkbuttonconf), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label43 = gtk_label_new (_("<span\n color=\"ORANGE\"font=\"11\"weight=\"bold\">CONFIRMER</span>"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox7), label43, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label42 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">Nbr des Places</span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed2), label42, 360, 288);
  gtk_widget_set_size_request (label42, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label_message = gtk_label_new ("");
  gtk_widget_show (label_message);
  gtk_fixed_put (GTK_FIXED (fixed2), label_message, 216, 384);
  gtk_widget_set_size_request (label_message, 248, 64);

  button_confmodpark = gtk_button_new ();
  gtk_widget_show (button_confmodpark);
  gtk_fixed_put (GTK_FIXED (fixed2), button_confmodpark, 472, 384);
  gtk_widget_set_size_request (button_confmodpark, 200, 64);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_confmodpark), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Confirmer Modification</span>"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox8), label45, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 0, 0);
  gtk_widget_set_size_request (button3, 40, 29);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (button3), image15);

  label47 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Ajouter un Parking</span>"));
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label47);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 24, 72);
  gtk_widget_set_size_request (treeview1, 600, 232);

  entry_search_park = gtk_entry_new ();
  gtk_widget_show (entry_search_park);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_search_park, 168, 368);
  gtk_widget_set_size_request (entry_search_park, 160, 40);
  gtk_entry_set_text (GTK_ENTRY (entry_search_park), _("1"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_search_park), 8226);

  btn_supp = gtk_button_new ();
  gtk_widget_show (btn_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_supp, 520, 16);
  gtk_widget_set_size_request (btn_supp, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (btn_supp), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Supprimer</span>"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox4), label51, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  btn_modif = gtk_button_new ();
  gtk_widget_show (btn_modif);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_modif, 272, 16);
  gtk_widget_set_size_request (btn_modif, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_modif), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-color-picker", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Modifier</span>"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox3), label50, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  btn_search_park = gtk_button_new ();
  gtk_widget_show (btn_search_park);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_search_park, 328, 368);
  gtk_widget_set_size_request (btn_search_park, 120, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_search_park), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image9 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox5), image9, FALSE, FALSE, 0);

  label53 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Rechercher</span>"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox5), label53, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  btn_aff = gtk_button_new ();
  gtk_widget_show (btn_aff);
  gtk_fixed_put (GTK_FIXED (fixed3), btn_aff, 24, 16);
  gtk_widget_set_size_request (btn_aff, 104, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_aff), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label49 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Afficher</span>"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox6), label49, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label52 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">ID</span>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed3), label52, 104, 368);
  gtk_widget_set_size_request (label52, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label46 = gtk_label_new (_("<span\n color=\"black\"font=\"11\"weight=\"bold\">Afficher les Parking</span>"));
  gtk_widget_show (label46);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label46);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview3, 216, 88);
  gtk_widget_set_size_request (treeview3, 272, 232);

  entry_nom_agent = gtk_entry_new ();
  gtk_widget_show (entry_nom_agent);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nom_agent, 192, 8);
  gtk_widget_set_size_request (entry_nom_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_agent), 8226);

  entry_id_agent = gtk_entry_new ();
  gtk_widget_show (entry_id_agent);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_id_agent, 192, 40);
  gtk_widget_set_size_request (entry_id_agent, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_agent), 8226);

  entry_nom_parking = gtk_entry_new ();
  gtk_widget_show (entry_nom_parking);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_nom_parking, 480, 24);
  gtk_widget_set_size_request (entry_nom_parking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_parking), 8226);

  label54 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">NOM AGENT</span>"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed4), label54, 88, 8);
  gtk_widget_set_size_request (label54, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  label55 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"normal\">ID AGENT</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed4), label55, 88, 8);
  gtk_widget_set_size_request (label55, 72, 104);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label56 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"NORMAL\">NOM PARKING</span>"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 376, 32);
  gtk_widget_set_size_request (label56, 100, 17);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed4), button1, 64, 328);
  gtk_widget_set_size_request (button1, 152, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button1), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">AJOUTER AGENT</span>"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox9), label57, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 488, 328);
  gtk_widget_set_size_request (button2, 170, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label58 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">AFFICHER AGENT</span>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox10), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  label48 = gtk_label_new (_("<span\n color=\"BLACK\"font=\"11\"weight=\"bold\">Assigne un Agent</span>"));
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label48);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  g_signal_connect ((gpointer) btn_ajouterpark, "clicked",
                    G_CALLBACK (on_btn_ajouterpark_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonconf, "toggled",
                    G_CALLBACK (on_checkbuttonconf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_confmodpark, "clicked",
                    G_CALLBACK (on_button_confmodpark_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_supp, "clicked",
                    G_CALLBACK (on_btn_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modif, "clicked",
                    G_CALLBACK (on_btn_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_search_park, "clicked",
                    G_CALLBACK (on_btn_search_park_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_aff, "clicked",
                    G_CALLBACK (on_btn_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Parking, Parking, "Parking");
  GLADE_HOOKUP_OBJECT (Parking, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Parking, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Parking, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Parking, entry_nompark, "entry_nompark");
  GLADE_HOOKUP_OBJECT (Parking, entry_idpark, "entry_idpark");
  GLADE_HOOKUP_OBJECT (Parking, entry_nbrdispopark, "entry_nbrdispopark");
  GLADE_HOOKUP_OBJECT (Parking, entry_prixpark, "entry_prixpark");
  GLADE_HOOKUP_OBJECT (Parking, labelmsg, "labelmsg");
  GLADE_HOOKUP_OBJECT (Parking, combobox_typepark, "combobox_typepark");
  GLADE_HOOKUP_OBJECT (Parking, combobox_etatpark, "combobox_etatpark");
  GLADE_HOOKUP_OBJECT (Parking, entry_capacite, "entry_capacite");
  GLADE_HOOKUP_OBJECT (Parking, btn_ajouterpark, "btn_ajouterpark");
  GLADE_HOOKUP_OBJECT (Parking, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Parking, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Parking, image1, "image1");
  GLADE_HOOKUP_OBJECT (Parking, label44, "label44");
  GLADE_HOOKUP_OBJECT (Parking, label16, "label16");
  GLADE_HOOKUP_OBJECT (Parking, label40, "label40");
  GLADE_HOOKUP_OBJECT (Parking, label39, "label39");
  GLADE_HOOKUP_OBJECT (Parking, label36, "label36");
  GLADE_HOOKUP_OBJECT (Parking, label37, "label37");
  GLADE_HOOKUP_OBJECT (Parking, label38, "label38");
  GLADE_HOOKUP_OBJECT (Parking, label41, "label41");
  GLADE_HOOKUP_OBJECT (Parking, checkbuttonconf, "checkbuttonconf");
  GLADE_HOOKUP_OBJECT (Parking, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Parking, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Parking, image11, "image11");
  GLADE_HOOKUP_OBJECT (Parking, label43, "label43");
  GLADE_HOOKUP_OBJECT (Parking, label42, "label42");
  GLADE_HOOKUP_OBJECT (Parking, label_message, "label_message");
  GLADE_HOOKUP_OBJECT (Parking, button_confmodpark, "button_confmodpark");
  GLADE_HOOKUP_OBJECT (Parking, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Parking, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Parking, image12, "image12");
  GLADE_HOOKUP_OBJECT (Parking, label45, "label45");
  GLADE_HOOKUP_OBJECT (Parking, button3, "button3");
  GLADE_HOOKUP_OBJECT (Parking, image15, "image15");
  GLADE_HOOKUP_OBJECT (Parking, label47, "label47");
  GLADE_HOOKUP_OBJECT (Parking, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Parking, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Parking, entry_search_park, "entry_search_park");
  GLADE_HOOKUP_OBJECT (Parking, btn_supp, "btn_supp");
  GLADE_HOOKUP_OBJECT (Parking, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Parking, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Parking, image4, "image4");
  GLADE_HOOKUP_OBJECT (Parking, label51, "label51");
  GLADE_HOOKUP_OBJECT (Parking, btn_modif, "btn_modif");
  GLADE_HOOKUP_OBJECT (Parking, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Parking, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Parking, image3, "image3");
  GLADE_HOOKUP_OBJECT (Parking, label50, "label50");
  GLADE_HOOKUP_OBJECT (Parking, btn_search_park, "btn_search_park");
  GLADE_HOOKUP_OBJECT (Parking, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Parking, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Parking, image9, "image9");
  GLADE_HOOKUP_OBJECT (Parking, label53, "label53");
  GLADE_HOOKUP_OBJECT (Parking, btn_aff, "btn_aff");
  GLADE_HOOKUP_OBJECT (Parking, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Parking, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Parking, image10, "image10");
  GLADE_HOOKUP_OBJECT (Parking, label49, "label49");
  GLADE_HOOKUP_OBJECT (Parking, label52, "label52");
  GLADE_HOOKUP_OBJECT (Parking, label46, "label46");
  GLADE_HOOKUP_OBJECT (Parking, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Parking, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Parking, entry_nom_agent, "entry_nom_agent");
  GLADE_HOOKUP_OBJECT (Parking, entry_id_agent, "entry_id_agent");
  GLADE_HOOKUP_OBJECT (Parking, entry_nom_parking, "entry_nom_parking");
  GLADE_HOOKUP_OBJECT (Parking, label54, "label54");
  GLADE_HOOKUP_OBJECT (Parking, label55, "label55");
  GLADE_HOOKUP_OBJECT (Parking, label56, "label56");
  GLADE_HOOKUP_OBJECT (Parking, button1, "button1");
  GLADE_HOOKUP_OBJECT (Parking, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Parking, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Parking, image13, "image13");
  GLADE_HOOKUP_OBJECT (Parking, label57, "label57");
  GLADE_HOOKUP_OBJECT (Parking, button2, "button2");
  GLADE_HOOKUP_OBJECT (Parking, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Parking, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Parking, image14, "image14");
  GLADE_HOOKUP_OBJECT (Parking, label58, "label58");
  GLADE_HOOKUP_OBJECT (Parking, label48, "label48");

  return Parking;
}



/////////////////////////////





GtkWidget*
create_RHwindowParky (void)
{
  GtkWidget *RHwindowParky;
  GtkWidget *fixed1;
  GtkWidget *RHlabelParky;
  GtkWidget *RHbuttonAvis_ReclamationCitoyen;
  GtkWidget *RHbuttonG__rerReservationCitoyen;

  RHwindowParky = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RHwindowParky), _("PARKY"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (RHwindowParky), fixed1);

  RHlabelParky = gtk_label_new (_("PARKY"));
  gtk_widget_show (RHlabelParky);
  gtk_fixed_put (GTK_FIXED (fixed1), RHlabelParky, 520, 32);
  gtk_widget_set_size_request (RHlabelParky, 70, 35);

  RHbuttonAvis_ReclamationCitoyen = gtk_button_new_with_mnemonic (_("Avis et reclamation"));
  gtk_widget_show (RHbuttonAvis_ReclamationCitoyen);
  gtk_fixed_put (GTK_FIXED (fixed1), RHbuttonAvis_ReclamationCitoyen, 456, 200);
  gtk_widget_set_size_request (RHbuttonAvis_ReclamationCitoyen, 170, 40);

  RHbuttonG__rerReservationCitoyen = gtk_button_new_with_mnemonic (_("Ajouter Parking"));
  gtk_widget_show (RHbuttonG__rerReservationCitoyen);
  gtk_fixed_put (GTK_FIXED (fixed1), RHbuttonG__rerReservationCitoyen, 456, 112);
  gtk_widget_set_size_request (RHbuttonG__rerReservationCitoyen, 170, 40);

  g_signal_connect ((gpointer) RHbuttonAvis_ReclamationCitoyen, "clicked",
                    G_CALLBACK (on_RHbuttonAvis_ReclamationCitoyen_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonG__rerReservationCitoyen, "clicked",
                    G_CALLBACK (on_RHbuttonG__rerReservationCitoyen_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RHwindowParky, RHwindowParky, "RHwindowParky");
  GLADE_HOOKUP_OBJECT (RHwindowParky, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (RHwindowParky, RHlabelParky, "RHlabelParky");
  GLADE_HOOKUP_OBJECT (RHwindowParky, RHbuttonAvis_ReclamationCitoyen, "RHbuttonAvis_ReclamationCitoyen");
  GLADE_HOOKUP_OBJECT (RHwindowParky, RHbuttonG__rerReservationCitoyen, "RHbuttonG__rerReservationCitoyen");

  return RHwindowParky;
}

GtkWidget*
create_RHwindowAvis_Reclamation (void)
{
  GtkWidget *RHwindowAvis_Reclamation;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *RHentryDescriptionAjouterReclamation;
  GtkWidget *RHentryCINAjouterReclamation;
  GtkWidget *RHentryIdClientAjouterReclamation;
  GtkWidget *RHlabelMsgEnregistrementAjouterReclamation;
  GtkWidget *RHbuttonEnregistrerAjouterReclamation;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label21;
  GtkWidget *RHlabelIdAjouterReclamation;
  GtkWidget *RHlabelNomParkingAjouterReclamation;
  GtkWidget *RHlabelSujetAjouterSujetReclamation;
  GtkWidget *RHlabelDescriptionAjouterReclamation;
  GtkWidget *RHlabelCINAjouterReclamation;
  GtkWidget *RHlabelUrgenceAjouterReclamation;
  GtkWidget *RHlabelNomApplicationAjouterReclamation;
  GtkWidget *RHcomboboxNomParkingAjouterReclamation;
  GtkWidget *RHcomboboxSujetAjouterReclamation;
  GtkWidget *RHradiobuttonBasseUrgenceAjouterReclamation;
  GSList *RHradiobuttonBasseUrgenceAjouterReclamation_group = NULL;
  GtkWidget *RHradiobuttonMoyenneUrgenceAjouterReclamation;
  GtkWidget *RHradiobuttonHauteUrgenceAjouterReclamation;
  GtkWidget *RHbuttonRetourWindowPrincipal;
  GtkWidget *image10;
  GtkWidget *RHlabelAjouterReclamation;
  GtkWidget *fixed3;
  GtkWidget *RHentryIdReclamationModifierReclamation;
  GtkWidget *RHentryDescriptionProbModifierReclamation;
  GtkWidget *RHentryCinModifierReclamation;
  GtkWidget *RHbuttonEnregistrerModifierReclamation;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label16;
  GtkWidget *RHlabelMsgModificationReclamation;
  GtkWidget *RHlabelIdModifierReclamation;
  GtkWidget *label17;
  GtkWidget *RHlabelIdReclamationModifierReclamation;
  GtkWidget *RHlabelIdClientModifierReclamation;
  GtkWidget *RHlabelNomParkingModifierReclamation;
  GtkWidget *RHlabelSujetModifierReclamation;
  GtkWidget *RHlabelDescriptionProblemeModifierReclamation;
  GtkWidget *RHlabelCINModifierReclamation;
  GtkWidget *RHlabelUrgenceModifierReclamation;
  GtkWidget *RHcomboboxNomParkingModifierReclamation;
  GtkWidget *RHcomboboxSujetModifierReclamation;
  GtkWidget *RHbuttonChercherIdModifierReclamation;
  GtkWidget *image4;
  GtkWidget *RHradiobuttonBasseModifierReclamation;
  GtkWidget *RHradiobuttonHauteModifierReclamation;
  GtkWidget *RHradiobuttonMoyenneModifierReclamation;
  GtkWidget *RHlabelModifierReclamation;
  GtkWidget *fixed4;
  GtkObject *RHspinbuttonJourSupprimerReclamation_adj;
  GtkWidget *RHspinbuttonJourSupprimerReclamation;
  GtkObject *RHspinbuttonMoisSupprimerReclamation_adj;
  GtkWidget *RHspinbuttonMoisSupprimerReclamation;
  GtkObject *RHspinbuttonAnneeSupprimerReclamation_adj;
  GtkWidget *RHspinbuttonAnneeSupprimerReclamation;
  GtkWidget *RHentryIdReclamationSupprimer;
  GtkWidget *RHlabelReclamationTrouveSupprimer;
  GtkWidget *label18;
  GtkWidget *RHlabelSelectionneDateSupprimerReclamation;
  GtkWidget *label5;
  GtkWidget *RHlabelMoisSupprimerReclamation;
  GtkWidget *RHlabelJoursSupprimerReclamation;
  GtkWidget *RHlabelAnneeSupprimerReclamation;
  GtkWidget *RHbuttonChercherReclamationSuprrimer;
  GtkWidget *image8;
  GtkWidget *RHlabelSelectionneReclamationSupprimerReclamation;
  GtkWidget *RHcheckbuttonReclamationSupprimer;
  GtkWidget *RHbuttonSupprimerReclamation;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label22;
  GtkWidget *RHlabelMessageConfirmationSupprimerReclamation;
  GtkWidget *RHlabelSupprimerReclamation;
  GtkWidget *fixed5;
  GtkWidget *RHtreeviewAfficherReclamation;
  GtkWidget *RHentryIdClientAfficherReclamation;
  GtkWidget *label19;
  GtkWidget *RHlabelIdClientAfficherReclamation;
  GtkWidget *RHbuttonChercherIdAfficherReclamation;
  GtkWidget *image2;
  GtkWidget *RHbuttonAfficherReclamation;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *RHlabelAfficherReclamation;
  GtkWidget *fixed6;
  GtkWidget *RHentryIdClientAvisReclamation;
  GtkWidget *RHlabelMsgEnregistrementAvis;
  GtkWidget *RHcheckbutton1;
  GtkWidget *RHcheckbutton2;
  GtkWidget *RHcheckbutton3;
  GtkWidget *RHcheckbutton4;
  GtkWidget *RHcheckbutton5;
  GtkWidget *label20;
  GtkWidget *RHlabelIdAvisReclamation;
  GtkWidget *RHcomboboxNomParkingAvisReclamation;
  GtkWidget *RHlabelNomParkingAvisReclamation;
  GtkWidget *RHlabelAvisAvisReclamation;
  GtkWidget *RHbuttonEnregistrementAvis;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *RHlabelAvisReclamation;

  RHwindowAvis_Reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (RHwindowAvis_Reclamation), _("Avis et Reclamation"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (RHwindowAvis_Reclamation), notebook1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  RHentryDescriptionAjouterReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryDescriptionAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHentryDescriptionAjouterReclamation, 536, 220);
  gtk_widget_set_size_request (RHentryDescriptionAjouterReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryDescriptionAjouterReclamation), 46);

  RHentryCINAjouterReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryCINAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHentryCINAjouterReclamation, 536, 270);
  gtk_widget_set_size_request (RHentryCINAjouterReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryCINAjouterReclamation), 8226);

  RHentryIdClientAjouterReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryIdClientAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHentryIdClientAjouterReclamation, 536, 72);
  gtk_widget_set_size_request (RHentryIdClientAjouterReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryIdClientAjouterReclamation), 8226);

  RHlabelMsgEnregistrementAjouterReclamation = gtk_label_new ("");
  gtk_widget_show (RHlabelMsgEnregistrementAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelMsgEnregistrementAjouterReclamation, 304, 512);
  gtk_widget_set_size_request (RHlabelMsgEnregistrementAjouterReclamation, 448, 41);

  RHbuttonEnregistrerAjouterReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonEnregistrerAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHbuttonEnregistrerAjouterReclamation, 500, 460);
  gtk_widget_set_size_request (RHbuttonEnregistrerAjouterReclamation, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (RHbuttonEnregistrerAjouterReclamation), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  RHlabelIdAjouterReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">votre ID:</span>"));
  gtk_widget_show (RHlabelIdAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelIdAjouterReclamation, 439, 73);
  gtk_widget_set_size_request (RHlabelIdAjouterReclamation, 75, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelIdAjouterReclamation), TRUE);

  RHlabelNomParkingAjouterReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Nom du parking \303\240 r\303\251clamm\303\251:</span>"));
  gtk_widget_show (RHlabelNomParkingAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelNomParkingAjouterReclamation, 295, 123);
  gtk_widget_set_size_request (RHlabelNomParkingAjouterReclamation, 225, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelNomParkingAjouterReclamation), TRUE);

  RHlabelSujetAjouterSujetReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Sujet:</span>"));
  gtk_widget_show (RHlabelSujetAjouterSujetReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelSujetAjouterSujetReclamation, 456, 171);
  gtk_widget_set_size_request (RHlabelSujetAjouterSujetReclamation, 60, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelSujetAjouterSujetReclamation), TRUE);

  RHlabelDescriptionAjouterReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Description du probleme:</span>"));
  gtk_widget_show (RHlabelDescriptionAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelDescriptionAjouterReclamation, 315, 223);
  gtk_widget_set_size_request (RHlabelDescriptionAjouterReclamation, 204, 24);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelDescriptionAjouterReclamation), TRUE);

  RHlabelCINAjouterReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">CIN:</span>"));
  gtk_widget_show (RHlabelCINAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelCINAjouterReclamation, 461, 271);
  gtk_widget_set_size_request (RHlabelCINAjouterReclamation, 60, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelCINAjouterReclamation), TRUE);

  RHlabelUrgenceAjouterReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Urgence:</span>"));
  gtk_widget_show (RHlabelUrgenceAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelUrgenceAjouterReclamation, 440, 328);
  gtk_widget_set_size_request (RHlabelUrgenceAjouterReclamation, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelUrgenceAjouterReclamation), TRUE);

  RHlabelNomApplicationAjouterReclamation = gtk_label_new (_("<span color =\"DARKBLUE\"font=\"12\"weight=\"bold\">Bienvenue dans PARKY</span>"));
  gtk_widget_show (RHlabelNomApplicationAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHlabelNomApplicationAjouterReclamation, 431, 15);
  gtk_widget_set_size_request (RHlabelNomApplicationAjouterReclamation, 220, 35);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelNomApplicationAjouterReclamation), TRUE);

  RHcomboboxNomParkingAjouterReclamation = gtk_combo_box_new_text ();
  gtk_widget_show (RHcomboboxNomParkingAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHcomboboxNomParkingAjouterReclamation, 536, 120);
  gtk_widget_set_size_request (RHcomboboxNomParkingAjouterReclamation, 220, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAjouterReclamation), _("Sous-sol (Ghazela)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAjouterReclamation), _("Etagier (Centre ville)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAjouterReclamation), _("priv\303\251 (Lac1)"));

  RHcomboboxSujetAjouterReclamation = gtk_combo_box_new_text ();
  gtk_widget_show (RHcomboboxSujetAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHcomboboxSujetAjouterReclamation, 536, 170);
  gtk_widget_set_size_request (RHcomboboxSujetAjouterReclamation, 220, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetAjouterReclamation), _("Retard"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetAjouterReclamation), _("Service"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetAjouterReclamation), _("Autre"));

  RHradiobuttonBasseUrgenceAjouterReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Basse"));
  gtk_widget_show (RHradiobuttonBasseUrgenceAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHradiobuttonBasseUrgenceAjouterReclamation, 536, 330);
  gtk_widget_set_size_request (RHradiobuttonBasseUrgenceAjouterReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonBasseUrgenceAjouterReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonBasseUrgenceAjouterReclamation));

  RHradiobuttonMoyenneUrgenceAjouterReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Moyenne"));
  gtk_widget_show (RHradiobuttonMoyenneUrgenceAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHradiobuttonMoyenneUrgenceAjouterReclamation, 536, 370);
  gtk_widget_set_size_request (RHradiobuttonMoyenneUrgenceAjouterReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonMoyenneUrgenceAjouterReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonMoyenneUrgenceAjouterReclamation));

  RHradiobuttonHauteUrgenceAjouterReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Haute"));
  gtk_widget_show (RHradiobuttonHauteUrgenceAjouterReclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), RHradiobuttonHauteUrgenceAjouterReclamation, 536, 410);
  gtk_widget_set_size_request (RHradiobuttonHauteUrgenceAjouterReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonHauteUrgenceAjouterReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonHauteUrgenceAjouterReclamation));

  RHbuttonRetourWindowPrincipal = gtk_button_new ();
  gtk_widget_show (RHbuttonRetourWindowPrincipal);
  gtk_fixed_put (GTK_FIXED (fixed2), RHbuttonRetourWindowPrincipal, 0, 0);
  gtk_widget_set_size_request (RHbuttonRetourWindowPrincipal, 40, 29);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (RHbuttonRetourWindowPrincipal), image10);

  RHlabelAjouterReclamation = gtk_label_new (_("Ajouter une reclamation"));
  gtk_widget_show (RHlabelAjouterReclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), RHlabelAjouterReclamation);
  gtk_widget_set_size_request (RHlabelAjouterReclamation, 200, 25);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  RHentryIdReclamationModifierReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryIdReclamationModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHentryIdReclamationModifierReclamation, 536, 72);
  gtk_widget_set_size_request (RHentryIdReclamationModifierReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryIdReclamationModifierReclamation), 8226);

  RHentryDescriptionProbModifierReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryDescriptionProbModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHentryDescriptionProbModifierReclamation, 536, 312);
  gtk_widget_set_size_request (RHentryDescriptionProbModifierReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryDescriptionProbModifierReclamation), 46);

  RHentryCinModifierReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryCinModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHentryCinModifierReclamation, 536, 360);
  gtk_widget_set_size_request (RHentryCinModifierReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryCinModifierReclamation), 8226);

  RHbuttonEnregistrerModifierReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonEnregistrerModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHbuttonEnregistrerModifierReclamation, 448, 560);
  gtk_widget_set_size_request (RHbuttonEnregistrerModifierReclamation, 100, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (RHbuttonEnregistrerModifierReclamation), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox3), label16, FALSE, FALSE, 0);

  RHlabelMsgModificationReclamation = gtk_label_new ("");
  gtk_widget_show (RHlabelMsgModificationReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelMsgModificationReclamation, 360, 624);
  gtk_widget_set_size_request (RHlabelMsgModificationReclamation, 270, 35);

  RHlabelIdModifierReclamation = gtk_label_new ("");
  gtk_widget_show (RHlabelIdModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelIdModifierReclamation, 536, 168);
  gtk_widget_set_size_request (RHlabelIdModifierReclamation, 220, 20);

  label17 = gtk_label_new (_("<span color =\"DARKBLUE\"font=\"12\"weight=\"bold\">Bienvenue dans PARKY</span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 431, 15);
  gtk_widget_set_size_request (label17, 220, 35);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  RHlabelIdReclamationModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">ID r\303\251clamation \303\240 modifier:</span>"));
  gtk_widget_show (RHlabelIdReclamationModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelIdReclamationModifierReclamation, 309, 72);
  gtk_widget_set_size_request (RHlabelIdReclamationModifierReclamation, 200, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelIdReclamationModifierReclamation), TRUE);

  RHlabelIdClientModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">votre ID:</span>"));
  gtk_widget_show (RHlabelIdClientModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelIdClientModifierReclamation, 435, 169);
  gtk_widget_set_size_request (RHlabelIdClientModifierReclamation, 70, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelIdClientModifierReclamation), TRUE);

  RHlabelNomParkingModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Nom du parking \303\240 r\303\251clamm\303\251:</span>"));
  gtk_widget_show (RHlabelNomParkingModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelNomParkingModifierReclamation, 291, 216);
  gtk_widget_set_size_request (RHlabelNomParkingModifierReclamation, 220, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelNomParkingModifierReclamation), TRUE);

  RHlabelSujetModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Sujet:</span>"));
  gtk_widget_show (RHlabelSujetModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelSujetModifierReclamation, 446, 264);
  gtk_widget_set_size_request (RHlabelSujetModifierReclamation, 60, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelSujetModifierReclamation), TRUE);

  RHlabelDescriptionProblemeModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Description du probleme:</span>"));
  gtk_widget_show (RHlabelDescriptionProblemeModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelDescriptionProblemeModifierReclamation, 306, 314);
  gtk_widget_set_size_request (RHlabelDescriptionProblemeModifierReclamation, 204, 24);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelDescriptionProblemeModifierReclamation), TRUE);

  RHlabelCINModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">CIN:</span>"));
  gtk_widget_show (RHlabelCINModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelCINModifierReclamation, 451, 360);
  gtk_widget_set_size_request (RHlabelCINModifierReclamation, 60, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelCINModifierReclamation), TRUE);

  RHlabelUrgenceModifierReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Urgence:</span>"));
  gtk_widget_show (RHlabelUrgenceModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHlabelUrgenceModifierReclamation, 436, 408);
  gtk_widget_set_size_request (RHlabelUrgenceModifierReclamation, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelUrgenceModifierReclamation), TRUE);

  RHcomboboxNomParkingModifierReclamation = gtk_combo_box_new_text ();
  gtk_widget_show (RHcomboboxNomParkingModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHcomboboxNomParkingModifierReclamation, 536, 216);
  gtk_widget_set_size_request (RHcomboboxNomParkingModifierReclamation, 220, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingModifierReclamation), _("Sous-sol (Ghazela)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingModifierReclamation), _("Etagier (Centre ville)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingModifierReclamation), _("priv\303\251 (Lac1)"));

  RHcomboboxSujetModifierReclamation = gtk_combo_box_new_text ();
  gtk_widget_show (RHcomboboxSujetModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHcomboboxSujetModifierReclamation, 536, 264);
  gtk_widget_set_size_request (RHcomboboxSujetModifierReclamation, 220, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetModifierReclamation), _("Retard"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetModifierReclamation), _("Service"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxSujetModifierReclamation), _("Autre"));

  RHbuttonChercherIdModifierReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonChercherIdModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHbuttonChercherIdModifierReclamation, 481, 117);
  gtk_widget_set_size_request (RHbuttonChercherIdModifierReclamation, 80, 30);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (RHbuttonChercherIdModifierReclamation), image4);

  RHradiobuttonBasseModifierReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Basse"));
  gtk_widget_show (RHradiobuttonBasseModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHradiobuttonBasseModifierReclamation, 536, 408);
  gtk_widget_set_size_request (RHradiobuttonBasseModifierReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonBasseModifierReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonBasseModifierReclamation));

  RHradiobuttonHauteModifierReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Haute"));
  gtk_widget_show (RHradiobuttonHauteModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHradiobuttonHauteModifierReclamation, 536, 496);
  gtk_widget_set_size_request (RHradiobuttonHauteModifierReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonHauteModifierReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonHauteModifierReclamation));

  RHradiobuttonMoyenneModifierReclamation = gtk_radio_button_new_with_mnemonic (NULL, _("Moyenne"));
  gtk_widget_show (RHradiobuttonMoyenneModifierReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), RHradiobuttonMoyenneModifierReclamation, 536, 450);
  gtk_widget_set_size_request (RHradiobuttonMoyenneModifierReclamation, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (RHradiobuttonMoyenneModifierReclamation), RHradiobuttonBasseUrgenceAjouterReclamation_group);
  RHradiobuttonBasseUrgenceAjouterReclamation_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (RHradiobuttonMoyenneModifierReclamation));

  RHlabelModifierReclamation = gtk_label_new (_("Modifier une reclamation"));
  gtk_widget_show (RHlabelModifierReclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), RHlabelModifierReclamation);
  gtk_widget_set_size_request (RHlabelModifierReclamation, 220, -1);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  RHspinbuttonJourSupprimerReclamation_adj = gtk_adjustment_new (31, 1, 31, 1, 10, 0);
  RHspinbuttonJourSupprimerReclamation = gtk_spin_button_new (GTK_ADJUSTMENT (RHspinbuttonJourSupprimerReclamation_adj), 1, 0);
  gtk_widget_show (RHspinbuttonJourSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHspinbuttonJourSupprimerReclamation, 536, 160);
  gtk_widget_set_size_request (RHspinbuttonJourSupprimerReclamation, 60, 27);

  RHspinbuttonMoisSupprimerReclamation_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 0);
  RHspinbuttonMoisSupprimerReclamation = gtk_spin_button_new (GTK_ADJUSTMENT (RHspinbuttonMoisSupprimerReclamation_adj), 1, 0);
  gtk_widget_show (RHspinbuttonMoisSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHspinbuttonMoisSupprimerReclamation, 616, 160);
  gtk_widget_set_size_request (RHspinbuttonMoisSupprimerReclamation, 60, 27);

  RHspinbuttonAnneeSupprimerReclamation_adj = gtk_adjustment_new (2024, 2000, 9999, 1, 10, 0);
  RHspinbuttonAnneeSupprimerReclamation = gtk_spin_button_new (GTK_ADJUSTMENT (RHspinbuttonAnneeSupprimerReclamation_adj), 1, 0);
  gtk_widget_show (RHspinbuttonAnneeSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHspinbuttonAnneeSupprimerReclamation, 696, 160);
  gtk_widget_set_size_request (RHspinbuttonAnneeSupprimerReclamation, 60, 27);

  RHentryIdReclamationSupprimer = gtk_entry_new ();
  gtk_widget_show (RHentryIdReclamationSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), RHentryIdReclamationSupprimer, 536, 72);
  gtk_widget_set_size_request (RHentryIdReclamationSupprimer, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryIdReclamationSupprimer), 8226);

  RHlabelReclamationTrouveSupprimer = gtk_label_new ("");
  gtk_widget_show (RHlabelReclamationTrouveSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelReclamationTrouveSupprimer, 384, 256);
  gtk_widget_set_size_request (RHlabelReclamationTrouveSupprimer, 320, 25);

  label18 = gtk_label_new (_("<span color =\"DARKBLUE\"font=\"12\"weight=\"bold\">Bienvenue dans PARKY</span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 431, 15);
  gtk_widget_set_size_request (label18, 220, 35);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  RHlabelSelectionneDateSupprimerReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Selectionn\303\251 la date de reclamation:</span>"));
  gtk_widget_show (RHlabelSelectionneDateSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelSelectionneDateSupprimerReclamation, 240, 152);
  gtk_widget_set_size_request (RHlabelSelectionneDateSupprimerReclamation, 280, 30);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelSelectionneDateSupprimerReclamation), TRUE);

  label5 = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">ID r\303\251clamation \303\240 supprimer:</span>"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 304, 72);
  gtk_widget_set_size_request (label5, 210, 25);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  RHlabelMoisSupprimerReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"10.5\"weight=\"bold\">Mois</span>"));
  gtk_widget_show (RHlabelMoisSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelMoisSupprimerReclamation, 614, 135);
  gtk_widget_set_size_request (RHlabelMoisSupprimerReclamation, 60, 20);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelMoisSupprimerReclamation), TRUE);

  RHlabelJoursSupprimerReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"10.5\"weight=\"bold\">Jours</span>"));
  gtk_widget_show (RHlabelJoursSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelJoursSupprimerReclamation, 534, 135);
  gtk_widget_set_size_request (RHlabelJoursSupprimerReclamation, 60, 20);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelJoursSupprimerReclamation), TRUE);

  RHlabelAnneeSupprimerReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"10.5\"weight=\"bold\">Annee</span>"));
  gtk_widget_show (RHlabelAnneeSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelAnneeSupprimerReclamation, 692, 135);
  gtk_widget_set_size_request (RHlabelAnneeSupprimerReclamation, 60, 20);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelAnneeSupprimerReclamation), TRUE);

  RHbuttonChercherReclamationSuprrimer = gtk_button_new ();
  gtk_widget_show (RHbuttonChercherReclamationSuprrimer);
  gtk_fixed_put (GTK_FIXED (fixed4), RHbuttonChercherReclamationSuprrimer, 480, 216);
  gtk_widget_set_size_request (RHbuttonChercherReclamationSuprrimer, 80, 30);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (RHbuttonChercherReclamationSuprrimer), image8);

  RHlabelSelectionneReclamationSupprimerReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Cocher la reclamation avec son sujet pour le supprimer:</span>"));
  gtk_widget_show (RHlabelSelectionneReclamationSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelSelectionneReclamationSupprimerReclamation, 112, 304);
  gtk_widget_set_size_request (RHlabelSelectionneReclamationSupprimerReclamation, 400, 30);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelSelectionneReclamationSupprimerReclamation), TRUE);

  RHcheckbuttonReclamationSupprimer = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (RHcheckbuttonReclamationSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), RHcheckbuttonReclamationSupprimer, 528, 312);
  gtk_widget_set_size_request (RHcheckbuttonReclamationSupprimer, 220, 28);

  RHbuttonSupprimerReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHbuttonSupprimerReclamation, 464, 384);
  gtk_widget_set_size_request (RHbuttonSupprimerReclamation, 120, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (RHbuttonSupprimerReclamation), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  RHlabelMessageConfirmationSupprimerReclamation = gtk_label_new ("");
  gtk_widget_show (RHlabelMessageConfirmationSupprimerReclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), RHlabelMessageConfirmationSupprimerReclamation, 304, 464);
  gtk_widget_set_size_request (RHlabelMessageConfirmationSupprimerReclamation, 450, 40);

  RHlabelSupprimerReclamation = gtk_label_new (_("Supprimer une reclamation"));
  gtk_widget_show (RHlabelSupprimerReclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), RHlabelSupprimerReclamation);
  gtk_widget_set_size_request (RHlabelSupprimerReclamation, 250, 30);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  RHtreeviewAfficherReclamation = gtk_tree_view_new ();
  gtk_widget_show (RHtreeviewAfficherReclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), RHtreeviewAfficherReclamation, 0, 184);
  gtk_widget_set_size_request (RHtreeviewAfficherReclamation, 1112, 296);

  RHentryIdClientAfficherReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryIdClientAfficherReclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), RHentryIdClientAfficherReclamation, 536, 72);
  gtk_widget_set_size_request (RHentryIdClientAfficherReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryIdClientAfficherReclamation), 8226);

  label19 = gtk_label_new (_("<span color =\"DARKBLUE\"font=\"12\"weight=\"bold\">Bienvenue dans PARKY</span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 431, 15);
  gtk_widget_set_size_request (label19, 220, 35);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  RHlabelIdClientAfficherReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">votre ID:</span>"));
  gtk_widget_show (RHlabelIdClientAfficherReclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), RHlabelIdClientAfficherReclamation, 422, 72);
  gtk_widget_set_size_request (RHlabelIdClientAfficherReclamation, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelIdClientAfficherReclamation), TRUE);

  RHbuttonChercherIdAfficherReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonChercherIdAfficherReclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), RHbuttonChercherIdAfficherReclamation, 481, 117);
  gtk_widget_set_size_request (RHbuttonChercherIdAfficherReclamation, 80, 30);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (RHbuttonChercherIdAfficherReclamation), image2);

  RHbuttonAfficherReclamation = gtk_button_new ();
  gtk_widget_show (RHbuttonAfficherReclamation);
  gtk_fixed_put (GTK_FIXED (fixed5), RHbuttonAfficherReclamation, 488, 496);
  gtk_widget_set_size_request (RHbuttonAfficherReclamation, 115, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (RHbuttonAfficherReclamation), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  RHlabelAfficherReclamation = gtk_label_new (_("Afficher mes reclamations"));
  gtk_widget_show (RHlabelAfficherReclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), RHlabelAfficherReclamation);
  gtk_widget_set_size_request (RHlabelAfficherReclamation, 210, 25);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  RHentryIdClientAvisReclamation = gtk_entry_new ();
  gtk_widget_show (RHentryIdClientAvisReclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), RHentryIdClientAvisReclamation, 536, 72);
  gtk_widget_set_size_request (RHentryIdClientAvisReclamation, 220, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (RHentryIdClientAvisReclamation), 8226);

  RHlabelMsgEnregistrementAvis = gtk_label_new ("");
  gtk_widget_show (RHlabelMsgEnregistrementAvis);
  gtk_fixed_put (GTK_FIXED (fixed6), RHlabelMsgEnregistrementAvis, 416, 408);
  gtk_widget_set_size_request (RHlabelMsgEnregistrementAvis, 300, 40);

  RHcheckbutton1 = gtk_check_button_new_with_mnemonic (_("Tr\303\251s insatisfait"));
  gtk_widget_show (RHcheckbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcheckbutton1, 528, 176);
  gtk_widget_set_size_request (RHcheckbutton1, 160, 24);

  RHcheckbutton2 = gtk_check_button_new_with_mnemonic (_("Insatisfait"));
  gtk_widget_show (RHcheckbutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcheckbutton2, 528, 216);
  gtk_widget_set_size_request (RHcheckbutton2, 140, 24);

  RHcheckbutton3 = gtk_check_button_new_with_mnemonic (_("Neutre"));
  gtk_widget_show (RHcheckbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcheckbutton3, 528, 256);
  gtk_widget_set_size_request (RHcheckbutton3, 118, 24);

  RHcheckbutton4 = gtk_check_button_new_with_mnemonic (_("Satisfait"));
  gtk_widget_show (RHcheckbutton4);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcheckbutton4, 528, 296);
  gtk_widget_set_size_request (RHcheckbutton4, 118, 24);

  RHcheckbutton5 = gtk_check_button_new_with_mnemonic (_("Tr\303\251s satisfait"));
  gtk_widget_show (RHcheckbutton5);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcheckbutton5, 528, 336);
  gtk_widget_set_size_request (RHcheckbutton5, 118, 24);

  label20 = gtk_label_new (_("<span color =\"DARKBLUE\"font=\"12\"weight=\"bold\">Bienvenue dans PARKY</span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 431, 15);
  gtk_widget_set_size_request (label20, 220, 35);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  RHlabelIdAvisReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">votre ID:</span>"));
  gtk_widget_show (RHlabelIdAvisReclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), RHlabelIdAvisReclamation, 434, 72);
  gtk_widget_set_size_request (RHlabelIdAvisReclamation, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelIdAvisReclamation), TRUE);

  RHcomboboxNomParkingAvisReclamation = gtk_combo_box_new_text ();
  gtk_widget_show (RHcomboboxNomParkingAvisReclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), RHcomboboxNomParkingAvisReclamation, 536, 120);
  gtk_widget_set_size_request (RHcomboboxNomParkingAvisReclamation, 220, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAvisReclamation), _("Sous-sol (Ghazela)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAvisReclamation), _("Etagier (Centre ville)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (RHcomboboxNomParkingAvisReclamation), _("priv\303\251 (Lac1)"));

  RHlabelNomParkingAvisReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Nom du parking:</span>"));
  gtk_widget_show (RHlabelNomParkingAvisReclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), RHlabelNomParkingAvisReclamation, 367, 120);
  gtk_widget_set_size_request (RHlabelNomParkingAvisReclamation, 160, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelNomParkingAvisReclamation), TRUE);

  RHlabelAvisAvisReclamation = gtk_label_new (_("<span color =\"BLACK\"font=\"11\"weight=\"bold\">Sujet:</span>"));
  gtk_widget_show (RHlabelAvisAvisReclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), RHlabelAvisAvisReclamation, 448, 173);
  gtk_widget_set_size_request (RHlabelAvisAvisReclamation, 60, 25);
  gtk_label_set_use_markup (GTK_LABEL (RHlabelAvisAvisReclamation), TRUE);

  RHbuttonEnregistrementAvis = gtk_button_new ();
  gtk_widget_show (RHbuttonEnregistrementAvis);
  gtk_fixed_put (GTK_FIXED (fixed6), RHbuttonEnregistrementAvis, 512, 472);
  gtk_widget_set_size_request (RHbuttonEnregistrementAvis, 115, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (RHbuttonEnregistrementAvis), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox6), label23, FALSE, FALSE, 0);

  RHlabelAvisReclamation = gtk_label_new (_("Avis"));
  gtk_widget_show (RHlabelAvisReclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), RHlabelAvisReclamation);
  gtk_widget_set_size_request (RHlabelAvisReclamation, 210, 25);

  g_signal_connect ((gpointer) RHbuttonEnregistrerAjouterReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonEnregistrerAjouterReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonBasseUrgenceAjouterReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonBasseUrgenceAjouterReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonMoyenneUrgenceAjouterReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonMoyenneUrgenceAjouterReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonHauteUrgenceAjouterReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonHauteUrgenceAjouterReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonRetourWindowPrincipal, "clicked",
                    G_CALLBACK (on_RHbuttonRetourWindowPrincipal_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonEnregistrerModifierReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonEnregistrerModifierReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonChercherIdModifierReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonChercherIdModifierReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonBasseModifierReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonBasseModifierReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonHauteModifierReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonHauteModifierReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHradiobuttonMoyenneModifierReclamation, "toggled",
                    G_CALLBACK (on_RHradiobuttonMoyenneModifierReclamation_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonChercherReclamationSuprrimer, "clicked",
                    G_CALLBACK (on_RHbuttonChercherReclamationSuprrimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbuttonReclamationSupprimer, "toggled",
                    G_CALLBACK (on_RHcheckbuttonReclamationSupprimer_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonSupprimerReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonSupprimerReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHtreeviewAfficherReclamation, "row_activated",
                    G_CALLBACK (on_RHtreeviewAfficherReclamation_row_activated),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonChercherIdAfficherReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonChercherIdAfficherReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonAfficherReclamation, "clicked",
                    G_CALLBACK (on_RHbuttonAfficherReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbutton1, "toggled",
                    G_CALLBACK (on_RHcheckbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbutton2, "toggled",
                    G_CALLBACK (on_RHcheckbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbutton3, "toggled",
                    G_CALLBACK (on_RHcheckbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbutton4, "toggled",
                    G_CALLBACK (on_RHcheckbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHcheckbutton5, "toggled",
                    G_CALLBACK (on_RHcheckbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) RHbuttonEnregistrementAvis, "clicked",
                    G_CALLBACK (on_RHbuttonEnregistrementAvis_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (RHwindowAvis_Reclamation, RHwindowAvis_Reclamation, "RHwindowAvis_Reclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryDescriptionAjouterReclamation, "RHentryDescriptionAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryCINAjouterReclamation, "RHentryCINAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryIdClientAjouterReclamation, "RHentryIdClientAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelMsgEnregistrementAjouterReclamation, "RHlabelMsgEnregistrementAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonEnregistrerAjouterReclamation, "RHbuttonEnregistrerAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image6, "image6");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label21, "label21");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdAjouterReclamation, "RHlabelIdAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelNomParkingAjouterReclamation, "RHlabelNomParkingAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelSujetAjouterSujetReclamation, "RHlabelSujetAjouterSujetReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelDescriptionAjouterReclamation, "RHlabelDescriptionAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelCINAjouterReclamation, "RHlabelCINAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelUrgenceAjouterReclamation, "RHlabelUrgenceAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelNomApplicationAjouterReclamation, "RHlabelNomApplicationAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcomboboxNomParkingAjouterReclamation, "RHcomboboxNomParkingAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcomboboxSujetAjouterReclamation, "RHcomboboxSujetAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonBasseUrgenceAjouterReclamation, "RHradiobuttonBasseUrgenceAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonMoyenneUrgenceAjouterReclamation, "RHradiobuttonMoyenneUrgenceAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonHauteUrgenceAjouterReclamation, "RHradiobuttonHauteUrgenceAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonRetourWindowPrincipal, "RHbuttonRetourWindowPrincipal");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image10, "image10");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelAjouterReclamation, "RHlabelAjouterReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryIdReclamationModifierReclamation, "RHentryIdReclamationModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryDescriptionProbModifierReclamation, "RHentryDescriptionProbModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryCinModifierReclamation, "RHentryCinModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonEnregistrerModifierReclamation, "RHbuttonEnregistrerModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image5, "image5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label16, "label16");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelMsgModificationReclamation, "RHlabelMsgModificationReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdModifierReclamation, "RHlabelIdModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label17, "label17");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdReclamationModifierReclamation, "RHlabelIdReclamationModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdClientModifierReclamation, "RHlabelIdClientModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelNomParkingModifierReclamation, "RHlabelNomParkingModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelSujetModifierReclamation, "RHlabelSujetModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelDescriptionProblemeModifierReclamation, "RHlabelDescriptionProblemeModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelCINModifierReclamation, "RHlabelCINModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelUrgenceModifierReclamation, "RHlabelUrgenceModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcomboboxNomParkingModifierReclamation, "RHcomboboxNomParkingModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcomboboxSujetModifierReclamation, "RHcomboboxSujetModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonChercherIdModifierReclamation, "RHbuttonChercherIdModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image4, "image4");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonBasseModifierReclamation, "RHradiobuttonBasseModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonHauteModifierReclamation, "RHradiobuttonHauteModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHradiobuttonMoyenneModifierReclamation, "RHradiobuttonMoyenneModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelModifierReclamation, "RHlabelModifierReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHspinbuttonJourSupprimerReclamation, "RHspinbuttonJourSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHspinbuttonMoisSupprimerReclamation, "RHspinbuttonMoisSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHspinbuttonAnneeSupprimerReclamation, "RHspinbuttonAnneeSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryIdReclamationSupprimer, "RHentryIdReclamationSupprimer");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelReclamationTrouveSupprimer, "RHlabelReclamationTrouveSupprimer");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label18, "label18");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelSelectionneDateSupprimerReclamation, "RHlabelSelectionneDateSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label5, "label5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelMoisSupprimerReclamation, "RHlabelMoisSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelJoursSupprimerReclamation, "RHlabelJoursSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelAnneeSupprimerReclamation, "RHlabelAnneeSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonChercherReclamationSuprrimer, "RHbuttonChercherReclamationSuprrimer");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image8, "image8");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelSelectionneReclamationSupprimerReclamation, "RHlabelSelectionneReclamationSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbuttonReclamationSupprimer, "RHcheckbuttonReclamationSupprimer");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonSupprimerReclamation, "RHbuttonSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image7, "image7");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label22, "label22");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelMessageConfirmationSupprimerReclamation, "RHlabelMessageConfirmationSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelSupprimerReclamation, "RHlabelSupprimerReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHtreeviewAfficherReclamation, "RHtreeviewAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryIdClientAfficherReclamation, "RHentryIdClientAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label19, "label19");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdClientAfficherReclamation, "RHlabelIdClientAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonChercherIdAfficherReclamation, "RHbuttonChercherIdAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image2, "image2");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonAfficherReclamation, "RHbuttonAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image1, "image1");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label8, "label8");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelAfficherReclamation, "RHlabelAfficherReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHentryIdClientAvisReclamation, "RHentryIdClientAvisReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelMsgEnregistrementAvis, "RHlabelMsgEnregistrementAvis");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbutton1, "RHcheckbutton1");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbutton2, "RHcheckbutton2");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbutton3, "RHcheckbutton3");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbutton4, "RHcheckbutton4");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcheckbutton5, "RHcheckbutton5");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label20, "label20");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelIdAvisReclamation, "RHlabelIdAvisReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHcomboboxNomParkingAvisReclamation, "RHcomboboxNomParkingAvisReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelNomParkingAvisReclamation, "RHlabelNomParkingAvisReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelAvisAvisReclamation, "RHlabelAvisAvisReclamation");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHbuttonEnregistrementAvis, "RHbuttonEnregistrementAvis");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, image9, "image9");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, label23, "label23");
  GLADE_HOOKUP_OBJECT (RHwindowAvis_Reclamation, RHlabelAvisReclamation, "RHlabelAvisReclamation");

  return RHwindowAvis_Reclamation;
}

